# Package Oververview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variables we are attempting to predict (survived)
target: survived

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v


features: 
  - pclass
  - sex
  - age
  - sibsp
  - parch
  - fare
  - cabin
  - embarked
  - title

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

C: 0.0005

# list of variables to be used in the pipeline's transformers
numerical_variables:
  - age
  - fare

categorical_variables:
  - sex
  - cabin
  - embarked
  - title

cabin : 
  - cabin